export const enum Designation {
  SALES_ASSOCIATE = 'SALES_ASSOCIATE',

  CASHIER = 'CASHIER',

  STORE_MANAGER = 'STORE_MANAGER',

  INVENTORY_CONTROL_SPECIALIST = 'INVENTORY_CONTROL_SPECIALIST',

  ALL_IN_ONE = 'ALL_IN_ONE',
}
